### ISSUE TITLE
"Why does a script for extracting subtitles work on one CentOS 7 server (Server A), but on another CentOS 7 server (Server B), it indicates that there are no subtitles? What could be the reason for this?"

### ISSUE THREAD

**Issue by eblis0n** [jdepoix/youtube-transcript-api#332] opened 2024-09-18 16:02 UTC
from googleapiclient.discovery import build 
from googleapiclient.errors import HttpError
from youtube_transcript_api import YouTubeTranscriptApi

DEVELOPER_KEY = 'DEVELOPER_KEY'
youtube = build('youtube', 'v3', developerKey=DEVELOPER_KEY)

print(youtube)

channel_id = 'UCxW8eO79brdkeqwTvO09sBg'
playlists_response = youtube.playlists().list(
    part='snippet',
    channelId=channel_id,
    maxResults=50  
).execute()

print("playlists_response['items']：", playlists_response['items'])
next_page_token = None
for playlist in playlists_response['items']:
    playlist_id = playlist['id']
    playlist_title = playlist['snippet']['title']
    safe_playlist_title = ''.join([c for c in playlist_title if c.isalnum() or c in (' ', '_', '-')]).rstrip()
    print("safe_playlist_title：", safe_playlist_title)
    playlistitems_response = youtube.playlistItems().list(
        part='contentDetails',
        playlistId=playlist_id,
        maxResults=50,
        pageToken=next_page_token
    ).execute()

    video = playlistitems_response['items']
    print(f"这个{playlist_id}下，共有{len(video)} 个视频")
    try:

        video_id = video[0]['contentDetails']['videoId']
        print("video_id",video_id)
        video_info = youtube.videos().list(part='contentDetails', id=video_id).execute()
        video_duration = video_info['items'][0]['contentDetails']['duration']
        data = YouTubeTranscriptApi.get_transcript(video_id, languages=['ja', 'en'])
        print(data)
    except Exception as e:
        print("e",e)
        
 
this script， on   PEG-HK PEG-HK  centos7 server  or  mac book can get_transcript ; but  on ali HK  centos7 server :Traceback (most recent call last):
File "/home/python/test2.py", line 37, in <module>
transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/youtube_transcript_api/_api.py", line 71, in list_transcripts
return TranscriptListFetcher(http_client).fetch(video_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/youtube_transcript_api/_transcripts.py", line 48, in fetch
self._extract_captions_json(self._fetch_video_html(video_id), video_id),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/youtube_transcript_api/_transcripts.py", line 62, in _extract_captions_json
raise TranscriptsDisabled(video_id)
youtube_transcript_api._errors.TranscriptsDisabled:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=30bOB-TeOYU! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!     

i had  change any  centos7 server  can't  get_transcript!!!help,why

**Comment by jdepoix** [comment] 2024-09-18 16:07
Duplicate of #303

**Closed by jdepoix** 2024-09-18 16:07 UTC
