### ISSUE TITLE
automatically generated  not support

### ISSUE THREAD

**Issue by lengrongfu** [jdepoix/youtube-transcript-api#178] opened 2022-12-14 10:44 UTC
# To Reproduce

### What code / cli command are you executing?

# Expected behavior
Describe what you expected to happen.

# Actual behaviour
Describe what is happening instead of the **Expected behavior**. Add error messages if there are any.

**Comment by jdepoix** [comment] 2022-12-14 11:42
@lengrongfu please properly describe what is not working as expected using the template I inserted.

**Comment by lengrongfu** [comment] 2022-12-14 12:28
@jdepoix Hi, Youtube translated subtitles to be downloaded?
e.g.
```
transcript_list = YouTubeTranscriptApi.list_transcripts(video_id="8iYCp3ZwoU8")
print(transcript_list)
For this video (8iYCp3ZwoU8) transcripts are available in the following languages:

(MANUALLY CREATED)
None

(GENERATED)
 - en ("English (auto-generated)")[TRANSLATABLE]

(TRANSLATION LANGUAGES)
 - af ("Afrikaans")
 - ak ("Akan")
 - sq ("Albanian")
 - am ("Amharic")
```

but `transcript = YouTubeTranscriptApi.get_transcript(video_id="8iYCp3ZwoU8", languages=['af'])` donot download.

**Comment by jdepoix** [comment] 2022-12-14 12:32
This is correct since there is no (manually nor automatically generated) transcript in Afrikaans. There only is an automatically generated English transcript, which can be translated into Afrikaans. To do so, [please have a look at the README](https://github.com/jdepoix/youtube-transcript-api#translate-transcript).

I will close this now, as this seems to work as intended.

**Closed by jdepoix** 2022-12-14 12:32 UTC
