### ISSUE TITLE
Error Working With Azure Functions

### ISSUE THREAD

**Issue by jdayhuff01** [jdepoix/youtube-transcript-api#338] opened 2024-09-25 01:32 UTC
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce

1. Create azure function triggered by an HTTP Request locally that inputs a video id and outputs the transcript of that video, make sure that the function is working on your local machine
2. Upload to Azure Function's and try to trigger using an HTTP Request 

### What code / cli command are you executing?
```
import azure.functions as func
import logging


app = func.FunctionApp(http_auth_level=func.AuthLevel.FUNCTION)

@app.route(route="azure_function/{video_id}")
def azure_function(req: func.HttpRequest) -> func.HttpResponse:
    from openai import OpenAI
    import json
    from youtube_transcript_api import YouTubeTranscriptApi
   
    video_id = req.route_params.get("video_id", None)
    
    #Input video_id and output a string transcription of audio
    def transcribe_video(video_id):
        transcript_dict = YouTubeTranscriptApi.get_transcript(video_id)
        
        transcript = ""
        for line in transcript_dict:
            transcript += line["text"] + " "
        return transcript

    logging.info("... starting transcription...")
    video_transcription = transcribe_video(video_id)
```

### Which Python version are you using?
Python 3.11.9

### Which version of youtube-transcript-api are you using?
youtube-transcript-api 0.6.2

# Expected behavior
Describe what you expected to happen. 

I expected to receive the english transcript of the video and output that into a string where I can then perform other analysis on it.

# Actual behaviour
The issue that I am having is that I am receiving a 500 error with this in the logging section

I have been able to sucessfully run this function on my local machine with the exact same video and others so I know its not an issue of the transcripts being disabled, however when I deploy to Azure I run into this error. I would venture to guess that this is probably an issue with the YouTube API taking issue with being run on a cloud platform but just wanted this confirmed and to see if there were any workarounds or if there are any other services that I could pull transcripts from YouTube video URL's that wouldnt have this issue.

# ... error message ...
Result: Failure Exception: TranscriptsDisabled: Could not retrieve a transcript for the video https://www.youtube.com/watch?v=Iq624DGZLyE! This is most likely caused by: Subtitles are disabled for this video If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!

Appreciate the help!!

**Comment by linxinli01** [comment] 2024-09-25 08:36
Having the same issue with Google Cloud functions as well...

**Comment by jdepoix** [comment] 2024-09-25 12:16
Duplicate of #303

**Closed by jdepoix** 2024-09-25 12:16 UTC
