### ISSUE TITLE
not getting transcript even tho its available

### ISSUE THREAD

**Issue by Uddhav07** [jdepoix/youtube-transcript-api#326] opened 2024-08-31 04:37 UTC
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce

### What code / cli command are you executing?
For example: I am running
```
    def transcribe_video(self) -> str:
        youtube_url = self.inputs[0].value
        try:
            video_id = self.extract_video_id(youtube_url)
            transcript = YouTubeTranscriptApi.get_transcript(video_id, languages=['en', 'hi'])
            full_transcript = " ".join([entry['text'] for entry in transcript])
            return full_transcript
        except Exception as e:
            return f"Error: {str(e)}"

```

### Which Python version are you using?
Python 3.12.4

### Which version of youtube-transcript-api are you using?
youtube-transcript-api 0.6.2

# Expected behavior
I expected to receive the english transcript

# Actual behaviour
```
Error: 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=yeCguJWHKVY! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
```

# list transcript answer

For this video (yeCguJWHKVY) transcripts are available in the following languages:

(MANUALLY CREATED)
 - en ("English")[TRANSLATABLE]

(GENERATED)
 - en ("English (auto-generated)")[TRANSLATABLE]

**Comment by jdepoix** [comment] 2024-08-31 08:46
Hi @Uddhav07,
does this happen for all videos or only this specific one? If it happens for all videos you are most likely encountering the same issue as in #303

**Comment by Uddhav07** [comment] 2024-08-31 08:55
> Hi @Uddhav07,
> does this happen for all videos or only this specific one? If it happens for all videos you are most likely encountering the same issue as in #303 

Yeah im using cloud server and therfa ing this on all videos

**Comment by jdepoix** [comment] 2024-08-31 09:07
Okay, then this is a duplicate of #303 .

**Closed by jdepoix** 2024-08-31 09:07 UTC
