### ISSUE TITLE
Retrieving YouTube Transcript from code residing in AWS Lambda Function

### ISSUE THREAD

**Issue by wg21908** [jdepoix/youtube-transcript-api#317] opened 2024-08-18 01:41 UTC
I run the following Python script locally, it works and prints the expected and desired results.  It is a very basic script that prints the transcript of a YouTube video, the ID of the video is hard-coded within the Python script on line 14.  The script is attached and is named get_transcript.pdf.

[get_transcript.pdf](https://github.com/user-attachments/files/16646923/get_transcript.pdf)

Running this script locally, was to just prove that I could get the desired results.  The ultimate goal is to run this type of code as a Lambda in "Amazon Web Services" (AWS).  The YouTube video ID will not be hard-coded for the AWS solution, but rather passed in as a variable.  I've converted the get_transcript code in an attempt to get it working within a Lambda in AWS.  The script is attached and is named lambda_function.pdf

[lambda_function.pdf](https://github.com/user-attachments/files/16646925/lambda_function.pdf)
  
### Which Python version are you using?
Locally, I am running Python 3.12.2.  For the AWS Lambda function, it uses 3.12.

### Which version of youtube-transcript-api are you using?
youtube-transcript-api 0.6.2

# Expected behavior
I would expect to get the same transcript results when the equivalent Python code is run within the AWS Lambda.  The good news is that the Lambda does receive a 200 level status code when using the same YouTube video ID that was hard-coded within my get_transcript.py script, but the Lambda does not provide the desired transcript like what is received when running the code locally.  

# Actual behaviour

The AWS Lambda does get a 200 level status code, but the transcript is not returned.  Since my Lambda is requesting the transcript for the same YouTube video ID that I requested when running the Python script locally on my machine, I would think I would get the same transcript.  However, I get this response from the API call.

{
  "statusCode": 200,
  "body": "Error fetching transcript: \nCould not retrieve a transcript for the video https://www.youtube.com/watch?v=XpFsMB6FoOs&t=12s&pp=ygUSTGludXggQm9vdCBQcm9jZXNz! This is most likely caused by:\n\nSubtitles are disabled for this video\n\nIf you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!"
}

Any advise or suggestions you can provide is greatly appreciated.

**Comment by jdepoix** [comment] 2024-08-18 05:57
Duplicate of #303

**Closed by jdepoix** 2024-08-18 05:57 UTC

**Comment by ZhukIvan** [comment] 2024-09-01 22:38
I have the same issue. I tested on multiple videos within multiple local environments - locally works perfectly fine, but on AWS Lambda I always get the "Subtitles are disabled for this video" error. Has anyone solved it ?

**Comment by DPLATA** [comment] 2024-12-04 00:40
> I have the same issue. I tested on multiple videos within multiple local environments - locally works perfectly fine, but on AWS Lambda I always get the "Subtitles are disabled for this video" error. Has anyone solved it ?

I just ran into this same issue has anyone solved it?

**Comment by ventz** [comment] 2024-12-13 20:53
Seeing the same issue here too, but within AWS Fargate (ECS)
