### ISSUE TITLE
Subtitles are disabled for this video

### ISSUE THREAD

**Issue by Skwara10** [jdepoix/youtube-transcript-api#350] opened 2024-11-14 23:20 UTC
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce
I am running the following Python code:
from youtube_transcript_api import YouTubeTranscriptApi

try:
    transcript = YouTubeTranscriptApi.get_transcript("KXtX-niRUmU", languages=["pl"])
    print(transcript)
except Exception as e:
    print(f"Error: {e}")

### What code / cli command are you executing?
For example: I am running
```
YouTubeTranscriptApi.get_transcript ...
```

### Which Python version are you using?
Python 3.9.2

### Which version of youtube-transcript-api are you using?
youtube-transcript-api 0.6.2

# Expected behavior
Describe what you expected to happen. 

I expected to receive the Polish transcript of the YouTube video with ID KXtX-niRUmU

# Actual behaviour
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=KXtX-niRUmU! 
This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, 
please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. 
Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. 
Also make sure that there are no open issues which already describe your problem!
```

**Comment by jdepoix** [comment] 2024-11-15 10:07
duplicate of #303

**Closed by jdepoix** 2024-11-15 10:07 UTC
