### ISSUE TITLE
youtube-transcript-api can't retrieve the video transcript (subtitles are disabled)???

### ISSUE THREAD

**Issue by mikeholp1987** [jdepoix/youtube-transcript-api#345] opened 2024-10-26 04:32 UTC
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce

### What code / cli command are you executing?
from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api.formatters import JSONFormatter

id = 'JElxE1u-ojo'

transcript = YouTubeTranscriptApi.get_transcript(id)
formatter = JSONFormatter()
json_formatted = formatter.format_transcript(transcript)

result = {'data': json_formatted}
print(result)

### Which Python version are you using?
Python 3.12.7

### Which version of youtube-transcript-api are you using?
youtube-transcript-api (latest version)

# Expected behavior
The code should display the full YouTube video transcript

For example: I expected to receive the english transcript

# Actual behaviour
It displays the following error:

For example: Instead I received the following error message:
The operation failed with an error. [400] Bad request. Please check your parameters. More details: Your code did not execute successfully: Traceback (most recent call last): File "/home/bun/app/sandbox/914887d6-e249-4f73-9997-876fa31b0115/0ck-code-app.py", line 8, in <module> transcript = YouTubeTranscriptApi.get_transcript(id) File "/home/bun/.local/lib/python3.9/site-packages/youtube_transcript_api/_api.py", line 137, in get_transcript return cls.list_transcripts(video_id, proxies, cookies).find_transcript(languages).fetch(preserve_formatting=preserve_formatting) File "/home/bun/.local/lib/python3.9/site-packages/youtube_transcript_api/_api.py", line 71, in list_transcripts return TranscriptListFetcher(http_client).fetch(video_id) File "/home/bun/.local/lib/python3.9/site-packages/youtube_transcript_api/_transcripts.py", line 48, in fetch self._extract_captions_json(self._fetch_video_html(video_id), video_id), File "/home/bun/.local/lib/python3.9/site-packages/youtube_transcript_api/_transcripts.py", line 62, in _extract_captions_json raise TranscriptsDisabled(video_id) youtube_transcript_api._errors.TranscriptsDisabled: Could not retrieve a transcript for the video https://www.youtube.com/watch?v=Op7Th100IY8! This is most likely caused by: Subtitles are disabled for this video If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!

**Comment by goingliveai** [comment] 2024-10-26 14:19
I am also getting this on some api calls, but not all. If I watch the video on youtube, the CC and transcript are available. This is the youtube id I used to get the error https://www.youtube.com/watch?v=W5fP-siGUVU

**Comment by wuzimi** [comment] 2024-10-27 08:07
I have the same problem.

**Comment by Scheeperscreepers** [comment] 2024-10-27 21:54
Same issue here...

**Comment by jdepoix** [comment] 2024-10-28 09:19
Duplicate of #303

**Closed by jdepoix** 2024-10-28 09:19 UTC

**Comment by tikene** [comment] 2024-11-30 22:19
I was having the same issue, ended up making a similar program, may not work in your case though since it also adds the subtitles to the video. It's more barebones than this repo but it works https://github.com/tikene/video-caption-and-translate - I'll delete this if linking other repos isnt allowed
