### ISSUE TITLE
TranscriptsDisabled on all videos that contain captions.

### ISSUE THREAD

**Issue by popeldd** [jdepoix/youtube-transcript-api#90] opened 2020-11-12 00:08 UTC
So, I just started using this and for some reason, I cannot find subtitles in any video that contains them. I do not know if you will be able to replicate this issue, but I will help as much as I can. I will continue reading through previously reported issues to see if anyone else has received it before. Thank you for your time!

Also, when I curl the link, I cannot find any transcriptions. (I tried to simplify the mess of the webpage to see if I missed them, a grep for the class "ytd-transcript-body-renderer" provides nothing.)

**A Sample Input:**
> YouTubeTranscriptApi.get_transcript('U7Xtmayoly8')

**Error:**
> Exception has occurred: TranscriptsDisabled
> 
> Could not retrieve a transcript for the video https://www.youtube.com/watch?v=U7Xtmayoly8! This is most likely caused by:
> 
> Subtitles are disabled for this video

**Comment by jdepoix** [comment] 2020-11-12 08:33
Hi @popeldd,
you changed the ID of the video you initially posted this issue for, are you sure you are still getting the same error with the video you changed it to?
Because the video you used initially (sOnqjkJTMaA) does have transcripts disabled, just like the error message says. However, the ID you are using now (U7Xtmayoly8) works for me without any problems and shouldn't get this error message.

**Comment by jdepoix** [comment] 2020-11-20 13:09
Any news on this @popeldd? Otherwise I will close this issue.

**Closed** 2020-11-30 07:56 UTC

**Comment by xq8ed** [comment] 2020-12-12 05:35
Is there any option for downloading auto-generated subs?

**Comment by jdepoix** [comment] 2020-12-12 07:57
@xq8ed Yes, there is. Please read [the docs on this](https://github.com/jdepoix/youtube-transcript-api#list-available-transcripts).

**Comment by xq8ed** [comment] 2020-12-12 11:34
@jdepoix  Is CLI mode supposed to download auto-generated subs? I don't see any option for that in docs.
I am using it in CLI and whenever i try to run it, it gives this :
`Could not retrieve a transcript for the video https://www.youtube.com/watch?v=18c3MTX0PK0! This is most likely caused by:

Subtitles are disabled for this video`
but on youtube there are auto-generated subs for this video.

**Comment by xq8ed** [comment] 2020-12-12 17:21
@jdepoix forgive me for my laziness I didn't use --language option
