### ISSUE TITLE
Huggingface Blocked

### ISSUE THREAD

**Issue by yourdesigncoza** [jdepoix/youtube-transcript-api#311] opened 2024-08-07 13:13 UTC
Not an ISSUE as such : YouTube seems to be blocking HugginFace as well , same as with DigitalOcean :::

**Comment by jdepoix** [comment] 2024-08-07 13:27
Hi, this is a duplicate of #303. The issue can be discussed over there.

**Closed by jdepoix** 2024-08-07 13:27 UTC
