### ISSUE TITLE
Auto Generated Transcripts

### ISSUE THREAD

**Issue by FVTAL** [jdepoix/youtube-transcript-api#360] opened 2024-12-19 22:06 UTC
Is there a specific way that this needs to be called in order to access them? It seems to have worked locally when I made a native_host.py file to route it, but when I try it on my flaskserver No matter what, I'm getting:

 python3 -c "from youtube_transcript_api import YouTubeTranscriptApi; print(YouTubeTranscriptApi.get_transcript('VIDEO_ID'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/www/flaskapp/venv/lib/python3.12/site-packages/youtube_transcript_api/_api.py", line 154, in get_transcript
    cls.list_transcripts(video_id, proxies, cookies)
  File "/var/www/flaskapp/venv/lib/python3.12/site-packages/youtube_transcript_api/_api.py", line 71, in list_transcripts
    return TranscriptListFetcher(http_client).fetch(video_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/flaskapp/venv/lib/python3.12/site-packages/youtube_transcript_api/_transcripts.py", line 49, in fetch
    self._extract_captions_json(self._fetch_video_html(video_id), video_id),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/flaskapp/venv/lib/python3.12/site-packages/youtube_transcript_api/_transcripts.py", line 63, in _extract_captions_json
    raise TranscriptsDisabled(video_id)
youtube_transcript_api._errors.TranscriptsDisabled: 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=VIDEO_ID! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
(venv) root@fvtal-host:/var/www/flaskapp# 

Does not matter where/how the command is formatted.

So wondering if the point is for it to be able to fetch auto generated transcripts regardless of this issue - why I can't.

Thanks

**Comment by jdepoix** [comment] 2024-12-20 08:34
duplicate of #303

**Closed by jdepoix** 2024-12-20 08:34 UTC
