### ISSUE TITLE
No transcript for video in Russian with  the folowing error

### ISSUE THREAD

**Issue by paulius777** [jdepoix/youtube-transcript-api#187] opened 2023-02-26 08:54 UTC
Hello,

Getting the following error when trying to get transcription for  this video https://www.youtube.com/watch?app=desktop&v=JoI2u646u84&ab_channel=DenisSemenikhin 
This is a video in Russian. I am using Chrome on Windows.

Your hekp would be much appreciated :), your tool is incredible ! Thanks for this.

:( Unknown error: Could not retrieve a transcript for the video http://www.youtube.com/watch?v=JoI2u646u84! This is most likely caused by: No transcripts were found for any of the requested language codes: ('en',) For this video (JoI2u646u84) transcripts are available in the following languages: (MANUALLY CREATED) None (GENERATED) - ru ("Russian (auto-generated)")[TRANSLATABLE] (TRANSLATION LANGUAGES) - af ("Afrikaans") - ak ("Akan") - sq ("Albanian") - am ("Amharic") - ar ("Arabic") - hy ("Armenian") - as ("Assamese") - ay ("Aymara") - az ("Azerbaijani") - bn ("Bangla") - eu ("Basque") - be ("Belarusian") - bho ("Bhojpuri") - bs ("Bosnian") - bg ("Bulgarian") - my ("Burmese") - ca ("Catalan") - ceb ("Cebuano") - zh-Hans ("Chinese (Simplified)") - zh-Hant ("Chinese (Traditional)") - co ("Corsican") - hr ("Croatian") - cs ("Czech") - da ("Danish") - dv ("Divehi") - nl ("Dutch") - en ("English") - eo ("Esperanto") - et ("Estonian") - ee ("Ewe") - fil ("Filipino") - fi ("Finnish") - fr ("French") - gl ("Galician") - lg ("Ganda") - ka ("Georgian") - de ("German") - el ("Greek") - gn ("Guarani") - gu ("Gujarati") - ht ("Haitian Creole") - ha ("Hausa") - haw ("Hawaiian") - iw ("Hebrew") - hi ("Hindi") - hmn ("Hmong") - hu ("Hungarian") - is ("Icelandic") - ig ("Igbo") - id ("Indonesian") - ga ("Irish") - it ("Italian") - ja ("Japanese") - jv ("Javanese") - kn ("Kannada") - kk ("Kazakh") - km ("Khmer") - rw ("Kinyarwanda") - ko ("Korean") - kri ("Krio") - ku ("Kurdish") - ky ("Kyrgyz") - lo ("Lao") - la ("Latin") - lv ("Latvian") - ln ("Lingala") - lt ("Lithuanian") - lb ("Luxembourgish") - mk ("Macedonian") - mg ("Malagasy") - ms ("Malay") - ml ("Malayalam") - mt ("Maltese") - mi ("Māori") - mr ("Marathi") - mn ("Mongolian") - ne ("Nepali") - nso ("Northern Sotho") - no ("Norwegian") - ny ("Nyanja") - or ("Odia") - om ("Oromo") - ps ("Pashto") - fa ("Persian") - pl ("Polish") - pt ("Portuguese") - pa ("Punjabi") - qu ("Quechua") - ro ("Romanian") - ru ("Russian") - sm ("Samoan") - sa ("Sanskrit") - gd ("Scottish Gaelic") - sr ("Serbian") - sn ("Shona") - sd ("Sindhi") - si ("Sinhala") - sk ("Slovak") - sl ("Slovenian") - so ("Somali") - st ("Southern Sotho") - es ("Spanish") - su ("Sundanese") - sw ("Swahili") - sv ("Swedish") - tg ("Tajik") - ta ("Tamil") - tt ("Tatar") - te ("Telugu") - th ("Thai") - ti ("Tigrinya") - ts ("Tsonga") - tr ("Turkish") - tk ("Turkmen") - uk ("Ukrainian") - ur ("Urdu") - ug ("Uyghur") - uz ("Uzbek") - vi ("Vietnamese") - cy ("Welsh") - fy ("Western Frisian") - xh ("Xhosa") - yi ("Yiddish") - yo ("Yoruba") - zu ("Zulu") If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!

**Comment by jdepoix** [comment] 2023-02-26 17:04
Hi @paulius777,
could you maybe share what you are executing? For me both the python code `YouTubeTranscriptApi.get_transcript("JoI2u646u84", languages=['ru'])`, as well as the CLI command `youtube_transcript_api JoI2u646u84 --languages ru` yield the desired result.

**Comment by paulius777** [comment] 2023-02-26 19:50
Hi @jdepoix,

I managed to get it usig CLI command from your answer. 
By the way is there a way to get it using graphical interface https://youtubetranscript.com/ ?

**Comment by jdepoix** [comment] 2023-02-26 22:18
@paulius777 I have no affiliation with that website, so I can't help you there, unfortunately.

I will close this now, as the issue is resolved.

**Closed by jdepoix** 2023-02-26 22:18 UTC

**Comment by paulius777** [comment] 2023-02-27 07:30
@jdepoix  thanks a lot !
