### ISSUE TITLE
Can't get subtitles for https://www.youtube.com/watch?v=Lls-ESp8-xo

### ISSUE THREAD

**Issue by yxw2014** [jdepoix/youtube-transcript-api#322] opened 2024-08-25 09:01 UTC
{\"source\": \"https://www.youtube.com/watch?v=Lls-ESp8-xo\", \"video_id\": \"Lls-ESp8-xo\", \"error\": \"\\nCould not retrieve a transcript for the video https://www.youtube.com/watch?v=Lls-ESp8-xo! This is most likely caused by:\\n\\nSubtitles are disabled for this video\\n\\nIf you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\"}

But it is not disabled!

**Comment by aj-bei** [comment] 2024-08-26 04:31
Are you running this locally or on the cloud?

**Comment by SAIM878** [comment] 2024-08-26 08:06
same issue faced during deployment on HuggingFace.
My code locally runs fine but not on HuggingFace.

**Comment by jdepoix** [comment] 2024-08-26 08:44
Duplicate of #303

**Closed by jdepoix** 2024-08-26 08:44 UTC
