### ISSUE TITLE
Error getting captions on Vercel

### ISSUE THREAD

**Issue by L1shed** [jdepoix/youtube-transcript-api#321] opened 2024-08-24 07:28 UTC
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce
- Do a simple WebAPI using FastAPI
- Deploy it on Vercel

Note that the WebAPI perfectly works in local

### What code / cli command are you executing?
I am running
```
subtitles = get_youtube_captions(str(url))
```
url's type is HttpUrl

### Which Python version are you using?
Python 3.12

### Which version of youtube-transcript-api are you using?
youtube-transcript-api 6.0.2

# Expected behavior
Return the subtitles if there are

# Actual behaviour
Instead I received the following warning:
```
Error getting captions: 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=ndAQfTzlVjc! This is most likely caused by:
Subtitles are disabled for this video
If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
```

**Comment by jdepoix** [comment] 2024-08-26 08:45
Duplicate of #303

**Closed by jdepoix** 2024-08-26 08:45 UTC
