### ISSUE TITLE
Failed to retrieve transcript

### ISSUE THREAD

**Issue by nasuf** [jdepoix/youtube-transcript-api#340] opened 2024-09-28 02:05 UTC
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce

### What code / cli command are you executing?
I am running
```
transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)
```

### Which Python version are you using?
Python 3.12.4

### Which version of youtube-transcript-api are you using?
youtube-transcript-api 0.6.2

# Expected behavior
I expected to receive all transcripts

# Actual behaviour
Instead I received the following error message:
```
ERROR:__main__:Error downloading transcript for video klqoz9w6cuA: 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=klqoz9w6cuA! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
ERROR:__main__:Unable to download transcript for video: https://www.youtube.com/watch?v=klqoz9w6cuA
```

**Comment by jdepoix** [comment] 2024-10-01 08:14
Hi @nasuf, does this happen for all videos, or only this specific one? If it happens for all videos this is probably a duplicate of #303.

**Comment by khushpatel2002** [comment] 2024-10-01 17:06
This is happening for most of the videos

**Comment by khushpatel2002** [comment] 2024-10-02 00:59
@jdepoix It is working on local, but not on ec2 or any servers...

**Comment by tejas122125** [comment] 2024-10-02 07:58
> @jdepoix It is working on local, but not on ec2 or any servers...

yeah i am also facing same error it is working on any local environment but not on aws servers. 
Any solutions ???

**Comment by jdepoix** [comment] 2024-10-02 08:37
Then this definitely is a duplicate of #303. Head over there to find more information!

**Closed by jdepoix** 2024-10-02 08:37 UTC
